# 老旧CUDA使用的镜像，CUDA10版本

FROM pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime

ENV DEBIAN_FRONTEND=noninteractive

# 使用清华源替换 apt 源
# RUN sed -i 's|http://archive.ubuntu.com/ubuntu/|https://mirrors.tuna.tsinghua.edu.cn/ubuntu/|g' /etc/apt/sources.list && \
#     sed -i 's|http://security.ubuntu.com/ubuntu/|https://mirrors.tuna.tsinghua.edu.cn/ubuntu/|g' /etc/apt/sources.list

# 安装基础工具 + 命令行 ffmpeg
RUN apt update && \
    apt install -y wget git pkg-config build-essential ffmpeg && \
    rm -rf /var/lib/apt/lists/*

# 1. Accept TOS for required channels
RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r

# 2. (Optional) Update conda after accepting TOS
RUN conda update -n base -c defaults conda -y

# 3. Install pyav
RUN conda install -y conda-forge::av && conda clean -afy
WORKDIR /app

# 配置 pip 使用清华源
# RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
#     pip config set install.trusted-host pypi.tuna.tsinghua.edu.cn

# 拷贝依赖文件并安装
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# 拷贝应用代码
COPY ./main.py . 

ENV WHISPER_MODEL=Systran/faster-whisper-large-v2
ENV DEVICE=cuda

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]