name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # 1️⃣ 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ 登录 GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3️⃣ 规范化仓库名（转小写）
      - name: Set lowercase repository name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      # 4️⃣ 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build --build-arg WHISPER_MODEL=Systran/faster-whisper-large-v2 -t ghcr.io/${REPO}/whisper-service:latest .

      # 5️⃣ 推送镜像到 GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/${REPO}/whisper-service:latest
