name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-cpu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and push CPU Docker image
        run: |
          DATE_TAG=$(date +%Y%m%d)
          IMAGE=ghcr.io/${REPO}/whisper-service
          docker build -f Dockerfile.cpu \
            -t $IMAGE:cpu-latest \
            -t $IMAGE:cpu-${DATE_TAG} .
          docker push $IMAGE:cpu-latest
          docker push $IMAGE:cpu-${DATE_TAG}

  build-gpu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base_image: 11.6.1-cudnn8-runtime-ubuntu20.04
            torch_version: 1.13.1
            torch_cuda_suffix: cu116
          - base_image: 12.3.2-cudnn9-runtime-ubuntu22.04
            torch_version: 2.8.0
            torch_cuda_suffix: cu121
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and push GPU Docker image
        run: |
          DATE_TAG=$(date +%Y%m%d)
          IMAGE=ghcr.io/${REPO}/whisper-service
          docker build -f Dockerfile.cuda \
            --build-arg BASE_IMAGE=${{ matrix.base_image }} \
            --build-arg TORCH_VERSION=${{ matrix.torch_version }} \
            --build-arg TORCH_CUDA_SUFFIX=${{ matrix.torch_cuda_suffix }} \
            -t $IMAGE:cuda${{ matrix.torch_cuda_suffix }}-latest \
            -t $IMAGE:cuda${{ matrix.torch_cuda_suffix }}-${DATE_TAG} .
          docker push $IMAGE:cuda${{ matrix.torch_cuda_suffix }}-latest
          docker push $IMAGE:cuda${{ matrix.torch_cuda_suffix }}-${DATE_TAG}
